### PR TITLE
Updated embedded redis dependency

### LINKED ISSUE #17: Outdated embedded redis dependency causes test failures as redis does not start
**Problem description**
Both RedisQosProfileServiceTest and SessionsControllerIntegrationTest fails as embedded redis does not startup

**Expected action**

1. Run mvn clean test
2. In the logs you will see
[ERROR] Errors:
[ERROR]   SessionsControllerIntegrationTest.setUp:158 » Runtime Can't start redis server. Check logs for details. Redis process log:
[ERROR]   RedisQosProfileServiceTest.setUp:61 » Runtime Can't start redis server. Check logs for details. Redis process log:
[INFO]
[ERROR] Tests run: 74, Failures: 0, Errors: 2, Skipped: 0
3. Caused by [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.119 s <<< FAILURE! -- in com.camara.qod.service.RedisQosProfileServiceTest
[ERROR] com.camara.qod.service.RedisQosProfileServiceTest -- Time elapsed: 0.119 s <<< ERROR!
java.lang.RuntimeException: Can't start redis server. Check logs for details. Redis process log:
	at redis.embedded.AbstractRedisInstance.awaitRedisServerReady(AbstractRedisInstance.java:70)
	at redis.embedded.AbstractRedisInstance.start(AbstractRedisInstance.java:42)
	at redis.embedded.RedisServer.start(RedisServer.java:9)
	at com.camara.qod.service.RedisQosProfileServiceTest.setUp(RedisQosProfileServiceTest.java:61)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

**Additional context**
This is happening on MacOS 14.5 and openjdk 17.0.2 2022-01-18

### PR DESCRIPTION
**Pull request by nashjain**
#### What type of PR is this?

* tests

#### What this PR does / why we need it:

it.ozimov.embedded-redis:0.7.3 seems outdated and the embedded redis server is not working. Replaced it with com.github.codemonstur.embedded-redis:1.4.3 which is a fork of it.ozimov.embedded-redis and is actively being maintained

#### Which issue(s) this PR fixes:

Fixes #17

### CODE REVIEW

**Comment by dfischer-tech** [comment]
Hi @nashjain,
As a minor workaround, simply replacing the line:
redisServer = new RedisServer(6370);
with:
RedisServer.builder().port(6370).setting("maxheap 128M").build();
would have sufficed.

However, I am generally in favour of updating outdated dependencies.
Therefore, I am satisfied with your pull request.

Cheers,
Domi

@reviewers: LGTM 👍

**Comment by maxl2287** [comment]
@nashjain LGTM from my side.
But can you please check if it's still working with the old dependency just using the heap?

```java
RedisServer.builder().port(6370).setting("maxheap 128M").build();
```

Because then we can update the tile of this PR, that it's not caused by an dependency.
It's more a heap-issue.

So we can use this PR as `update dependecies for embedded redis` or something like that.

Wdyt @nashjain ?

BR
Max

**Review by maxl2287 — APPROVED** [review]
LGTM

**Comment by nashjain** [comment]
> @nashjain LGTM from my side. But can you please check if it's still working with the old dependency just using the heap?
> 
> ```java
> RedisServer.builder().port(6370).setting("maxheap 128M").build();
> ```
> 
> Because then we can update the tile of this PR, that it's not caused by an dependency. It's more a heap-issue.
> 
> So we can use this PR as `update dependecies for embedded redis` or something like that.
> 
> Wdyt @nashjain ?
> 
> BR Max

Hi @maxl2287,

Even after updating the code to use RedisServer.builder().port(6370).setting("maxheap 128M").build();

I'm still getting this error:

java.lang.RuntimeException: Can't start redis server. Check logs for details. Redis process log:

at redis.embedded.AbstractRedisInstance.awaitRedisServerReady(AbstractRedisInstance.java:70)
at redis.embedded.AbstractRedisInstance.start(AbstractRedisInstance.java:42)
at redis.embedded.RedisServer.start(RedisServer.java:9)
at com.camara.qod.service.RedisQosProfileServiceTest.setUp(RedisQosProfileServiceTest.java:62)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Process finished with exit code 255

**Pull request merged**
